/** Split a display name into first/last for forms and account provisioning. */
export function splitDisplayName(name: string): { firstName: string; lastName: string } {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return { firstName: "user", lastName: "account" };
  if (parts.length === 1) return { firstName: parts[0]!, lastName: "user" };
  return { firstName: parts[0]!, lastName: parts.slice(1).join(" ") };
}

export function normalizeContactEmail(raw: string): string {
  return raw.trim().toLowerCase();
}

/** Default login handle for new accounts — the normalized contact email. */
export function loginUsernameFromContactEmail(contactEmail: string): string {
  return normalizeContactEmail(contactEmail);
}

/** Legacy auto-generated handles like `alex.morgan@syal-operations.local`. */
export function isLegacyAutoGeneratedUsername(username: string): boolean {
  return username.trim().toLowerCase().endsWith(".local");
}

/** Sign-in email shown in admin UI — hides obsolete generated usernames. */
export function employeeSignInEmail(username: string, contactEmail: string): string {
  const contact = normalizeContactEmail(contactEmail);
  const login = username.trim().toLowerCase();
  if (!login || login === contact || isLegacyAutoGeneratedUsername(login)) {
    return contact;
  }
  return login;
}
