/**
 * Rewrites legacy `*@*.local` employee usernames to their contact email (login handle).
 * Safe to run repeatedly — skips rows already using contact email.
 *
 * Run: npx tsx scripts/migrate-legacy-employee-usernames.ts
 */
import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import {
  isLegacyAutoGeneratedUsername,
  loginUsernameFromContactEmail,
} from "../lib/display-name";

const prisma = new PrismaClient();

async function main() {
  const employees = await prisma.employee.findMany({
    select: { id: true, username: true, contactEmail: true, userId: true },
  });

  let updated = 0;
  for (const employee of employees) {
    if (!isLegacyAutoGeneratedUsername(employee.username)) continue;

    const username = loginUsernameFromContactEmail(employee.contactEmail);
    if (username === employee.username) continue;

    const clash = await prisma.employee.findFirst({
      where: { username, NOT: { id: employee.id } },
      select: { id: true },
    });
    if (clash) {
      console.warn(
        `[migrate-legacy-employee-usernames] Skip ${employee.contactEmail}: username ${username} already taken`
      );
      continue;
    }

    await prisma.employee.update({
      where: { id: employee.id },
      data: { username },
    });

    if (employee.userId) {
      const userClash = await prisma.user.findFirst({
        where: { username, NOT: { id: employee.userId } },
        select: { id: true },
      });
      if (!userClash) {
        await prisma.user.update({
          where: { id: employee.userId },
          data: { username },
        });
      }
    }

    console.log(`[migrate-legacy-employee-usernames] ${employee.username} → ${username}`);
    updated++;
  }

  console.log(`[migrate-legacy-employee-usernames] Done. Updated ${updated} employee(s).`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
